### ISSUE TITLE
.NET 4.0 Nuget support

### ISSUE THREAD

**Issue by pcmantinker** [coreyauger/Neo4JMembershipProvider#2]
I'm attempting to install your membership provider through Nuget in Visual Studio 2013 for my ASP.NET MVC project, but I can't because my project is targetted at .NET 4.0. Can you update the Nuget package to target at least .NET 4.0 and possibly .NET 4.5?

**Comment by coreyauger** [comment]
When I install the package in an MVC 4 application it resolves to the 4.0 runtime.  (Visual Studio 2012).  Not sure why you are getting a problem.

**Comment by pcmantinker** [comment]
I've updated my project to use .NET 4.5 and it installed without issues. I looked through your packages.config and saw that all were pointing to .NET 4.5 so I decided to upgrade and see if that fixed the issue.

**Comment by coreyauger** [comment]
Ok let me know if you run into any problems.
